name: cordova-plugin-test

on:
	push:
		branches: [ master ]

jobs:
	build:
		runs-on: ubuntu-latest
		env:
			BUILD_NUMBER: ${{ github.run_number }}
		steps:
			- uses: actions/checkout@v2

			- uses: actions/setup-node@v2
				with:
					node-version: 14
			- run: cat package.json
