name: cordova-plugin-test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - package.json
      - plugin.xml
      - www/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: sed -i 's/\(\"version\"\:\s*\"*[0-9]*\.[0-9]*\.\)\([0-9]*\)\(\"\)/\1${{ env.BUILD_NUMBER }}\3/g' package.json
      - run: cat package.json
      - run: npm publish --access public
